# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-25 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='Type',
            field=models.CharField(default='USUALLY_OFF', max_length=11),
        ),
    ]
